/**
 * Mock data for ManualBot demo preview
 * Used when no backend API is available
 */

import type {
  User,
  Organization,
  Bot,
  Document,
  AnalyticsOverview,
  ChatResponse,
  WidgetToken,
  Citation,
} from "@/types";

export const DEMO_USER: User = {
  id: "usr_demo_001",
  email: "demo@manualbot.ai",
  full_name: "Alex Chen",
  is_active: true,
  is_verified: true,
  avatar_url: null,
  created_at: "2024-01-15T10:00:00Z",
};

export const DEMO_ORGANIZATION: Organization = {
  id: "org_demo_001",
  name: "Acme Corp",
  slug: "acme-corp",
  logo_url: null,
  website: "https://acme.example.com",
  plan: "pro",
  is_active: true,
  created_at: "2024-01-15T10:00:00Z",
};

export const DEMO_BOTS: Bot[] = [
  {
    id: "bot_001",
    organization_id: "org_demo_001",
    name: "Support Bot",
    greeting: "Hi! I'm your support assistant. How can I help you today?",
    brand_color: "#6366f1",
    logo_url: null,
    fallback_message: "I couldn't find an answer in the documentation. Let me connect you with a human agent.",
    system_prompt: "You are a helpful support assistant for Acme Corp.",
    is_active: true,
    chat_model: "gpt-4o-mini",
    temperature: 0.3,
    max_tokens: 1024,
    citation_mode: true,
    strict_mode: true,
    lead_capture: true,
    escalation_email: "support@acme.example.com",
    escalation_webhook: null,
    allowed_domains: ["acme.example.com", "docs.acme.example.com"],
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-03-05T14:30:00Z",
    document_count: 12,
    chunk_count: 2847,
  },
  {
    id: "bot_002",
    organization_id: "org_demo_001",
    name: "Sales Assistant",
    greeting: "Welcome! I can help you learn about our products and pricing.",
    brand_color: "#10b981",
    logo_url: null,
    fallback_message: null,
    system_prompt: "You are a knowledgeable sales assistant.",
    is_active: true,
    chat_model: "gpt-4o-mini",
    temperature: 0.5,
    max_tokens: 2048,
    citation_mode: true,
    strict_mode: false,
    lead_capture: true,
    escalation_email: "sales@acme.example.com",
    escalation_webhook: null,
    allowed_domains: null,
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-03-06T09:15:00Z",
    document_count: 8,
    chunk_count: 1523,
  },
  {
    id: "bot_003",
    organization_id: "org_demo_001",
    name: "Onboarding Guide",
    greeting: "Hey there! Let me help you get started with our platform.",
    brand_color: "#f59e0b",
    logo_url: null,
    fallback_message: null,
    system_prompt: null,
    is_active: false,
    chat_model: "gpt-4o-mini",
    temperature: 0.7,
    max_tokens: 1024,
    citation_mode: false,
    strict_mode: false,
    lead_capture: false,
    escalation_email: null,
    escalation_webhook: null,
    allowed_domains: null,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    document_count: 3,
    chunk_count: 456,
  },
];

export const DEMO_DOCUMENTS: Record<string, Document[]> = {
  bot_001: [
    {
      id: "doc_001",
      bot_id: "bot_001",
      organization_id: "org_demo_001",
      file_name: "getting-started-guide.pdf",
      original_file_name: "Getting Started Guide.pdf",
      file_size: 2457600,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 24,
      chunk_count: 187,
      error_message: null,
      created_at: "2024-02-01T11:00:00Z",
      updated_at: "2024-02-01T11:05:00Z",
    },
    {
      id: "doc_002",
      bot_id: "bot_001",
      organization_id: "org_demo_001",
      file_name: "api-reference-v2.pdf",
      original_file_name: "API Reference v2.pdf",
      file_size: 5242880,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 86,
      chunk_count: 642,
      error_message: null,
      created_at: "2024-02-02T09:00:00Z",
      updated_at: "2024-02-02T09:12:00Z",
    },
    {
      id: "doc_003",
      bot_id: "bot_001",
      organization_id: "org_demo_001",
      file_name: "troubleshooting-faq.pdf",
      original_file_name: "Troubleshooting FAQ.pdf",
      file_size: 1048576,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 15,
      chunk_count: 98,
      error_message: null,
      created_at: "2024-02-05T14:00:00Z",
      updated_at: "2024-02-05T14:03:00Z",
    },
    {
      id: "doc_004",
      bot_id: "bot_001",
      organization_id: "org_demo_001",
      file_name: "release-notes-2024.pdf",
      original_file_name: "Release Notes 2024.pdf",
      file_size: 819200,
      mime_type: "application/pdf",
      status: "processing",
      page_count: null,
      chunk_count: null,
      error_message: null,
      created_at: "2024-03-07T16:00:00Z",
      updated_at: "2024-03-07T16:00:00Z",
    },
    {
      id: "doc_005",
      bot_id: "bot_001",
      organization_id: "org_demo_001",
      file_name: "security-whitepaper.pdf",
      original_file_name: "Security Whitepaper.pdf",
      file_size: 3145728,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 42,
      chunk_count: 315,
      error_message: null,
      created_at: "2024-02-10T10:00:00Z",
      updated_at: "2024-02-10T10:08:00Z",
    },
  ],
  bot_002: [
    {
      id: "doc_010",
      bot_id: "bot_002",
      organization_id: "org_demo_001",
      file_name: "product-catalog-2024.pdf",
      original_file_name: "Product Catalog 2024.pdf",
      file_size: 8388608,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 64,
      chunk_count: 489,
      error_message: null,
      created_at: "2024-02-15T11:00:00Z",
      updated_at: "2024-02-15T11:15:00Z",
    },
    {
      id: "doc_011",
      bot_id: "bot_002",
      organization_id: "org_demo_001",
      file_name: "pricing-guide.pdf",
      original_file_name: "Pricing Guide.pdf",
      file_size: 1572864,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 12,
      chunk_count: 78,
      error_message: null,
      created_at: "2024-02-16T09:00:00Z",
      updated_at: "2024-02-16T09:02:00Z",
    },
  ],
  bot_003: [
    {
      id: "doc_020",
      bot_id: "bot_003",
      organization_id: "org_demo_001",
      file_name: "onboarding-checklist.pdf",
      original_file_name: "Onboarding Checklist.pdf",
      file_size: 524288,
      mime_type: "application/pdf",
      status: "completed",
      page_count: 8,
      chunk_count: 45,
      error_message: null,
      created_at: "2024-03-01T11:00:00Z",
      updated_at: "2024-03-01T11:01:00Z",
    },
  ],
};

export const DEMO_ANALYTICS: AnalyticsOverview = {
  docs_uploaded: 23,
  chunks_indexed: 4826,
  chats_today: 47,
  chats_total: 1284,
  active_bots: 2,
  top_questions: [
    { question: "How do I reset my password?", count: 89 },
    { question: "What are the pricing plans?", count: 67 },
    { question: "How to integrate the API?", count: 54 },
    { question: "Where can I find the documentation?", count: 43 },
    { question: "How do I cancel my subscription?", count: 38 },
    { question: "What payment methods do you accept?", count: 31 },
    { question: "How to export my data?", count: 27 },
    { question: "Is there a free trial?", count: 22 },
  ],
  unresolved_count: 12,
  avg_response_time_ms: 1250,
};

export const DEMO_WIDGET_TOKEN: WidgetToken = {
  id: "wt_001",
  bot_id: "bot_001",
  token: "mb_widget_demo_abc123xyz789",
  is_active: true,
  created_at: "2024-02-01T12:00:00Z",
};

const DEMO_CITATIONS: Citation[] = [
  {
    chunk_id: "chunk_001",
    document_id: "doc_001",
    file_name: "Getting Started Guide.pdf",
    page_number: 5,
    text_snippet: "To get started, navigate to the Dashboard and click 'Create New Bot'. Follow the setup wizard to configure your bot's name, greeting message, and brand color.",
    score: 0.94,
  },
  {
    chunk_id: "chunk_002",
    document_id: "doc_002",
    file_name: "API Reference v2.pdf",
    page_number: 12,
    text_snippet: "The Chat API endpoint accepts POST requests with a JSON body containing the message and optional session_token for conversation continuity.",
    score: 0.87,
  },
];

const CHAT_RESPONSES: Record<string, { answer: string; citations: Citation[]; answer_found: boolean }> = {
  default: {
    answer: "Based on the documentation, I can help you with that! The platform offers comprehensive tools for building AI chatbots. You can upload PDF documents, configure bot behavior, and embed chat widgets on your website. Would you like me to explain any specific feature in more detail?",
    citations: DEMO_CITATIONS,
    answer_found: true,
  },
  "what are the main features": {
    answer: "ManualBot offers several key features:\n\n1. **Document Upload** — Upload PDFs to create a knowledge base\n2. **AI Chat** — GPT-powered chatbot that answers from your docs\n3. **Citations** — Every answer includes source references\n4. **Embed Widget** — Add the chatbot to any website with a code snippet\n5. **Analytics** — Track usage, top questions, and resolution rates\n6. **Lead Capture** — Collect visitor information during chats\n7. **Domain Restrictions** — Control where your widget can be embedded",
    citations: [DEMO_CITATIONS[0]],
    answer_found: true,
  },
  "how do i get started": {
    answer: "Getting started is easy! Here's a quick guide:\n\n1. **Create a Bot** — Click 'New Bot' from the dashboard\n2. **Upload Documents** — Drag and drop your PDF files\n3. **Test Chat** — Try asking questions in the test chat\n4. **Embed** — Copy the widget code to your website\n\nThe AI will automatically index your documents and be ready to answer questions within minutes.",
    citations: [DEMO_CITATIONS[0]],
    answer_found: true,
  },
  "what are the system requirements": {
    answer: "ManualBot is a cloud-based platform, so there are minimal system requirements:\n\n- **Browser**: Chrome, Firefox, Safari, or Edge (latest versions)\n- **Documents**: PDF format, up to 50MB per file\n- **Widget**: Works on any website that supports JavaScript\n- **API**: RESTful API accessible from any programming language\n\nNo server-side installation is required.",
    citations: [DEMO_CITATIONS[1]],
    answer_found: true,
  },
  "how do i troubleshoot issues": {
    answer: "Here are common troubleshooting steps:\n\n1. **Bot not responding** — Check that the bot is set to 'Active' in settings\n2. **Poor answers** — Upload more relevant documentation\n3. **Widget not showing** — Verify the domain is in the allowed list\n4. **Upload failures** — Ensure files are PDF format and under 50MB\n\nIf issues persist, check the Analytics page for unresolved questions to identify knowledge gaps.",
    citations: DEMO_CITATIONS,
    answer_found: true,
  },
};

let chatMessageCounter = 0;

export function getMockChatResponse(message: string): ChatResponse {
  chatMessageCounter++;
  const key = message.toLowerCase().replace(/[?!.]/g, "").trim();
  const matched = CHAT_RESPONSES[key] || CHAT_RESPONSES.default;

  return {
    answer: matched.answer,
    session_token: "session_demo_" + Date.now(),
    message_id: "msg_" + chatMessageCounter + "_" + Date.now(),
    citations: matched.citations,
    sources: matched.citations.map((c) => c.file_name),
    answer_found: matched.answer_found,
    confidence: matched.answer_found ? "high" : "low",
    tokens_used: 150 + Math.floor(Math.random() * 200),
    latency_ms: 800 + Math.floor(Math.random() * 1200),
  };
}
